# Copyright (c) 2019-2024, The Khronos Group Inc.
# SPDX-License-Identifier: Apache-2.0

jobs:
  - job: check_codespell
    displayName: "codespell"
    pool:
      vmImage: "ubuntu-latest"
    container: khronosgroup/docker-images:openxr-sdk.20240805@sha256:bbc790ccdc56f291d72877c6fdb825edbb9c3222efb63dc4d3ac34e3bf13dd7a

    steps:
      - checkout: self
        lfs: true

      - script: ./checkCodespell
        displayName: Run Codespell script
